# Generated by Django 4.2.2 on 2023-06-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_especifica', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('serial', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=15)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.area')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Localizacion',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicacion'),
        ),
    ]
